(() => {
  const CART_KEY='aurelyne-cart-v1', WISH_KEY='aurelyne-wishlist-v1', body=document.body;
  const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
  const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const money=value=>`₹${Number(value).toLocaleString('en-IN')}`;
  const price=text=>Number((text||'').replace(/[^0-9]/g,'').slice(0,5))||0;
  let cart=read(CART_KEY), activeProduct=null;

  const ui=document.createElement('div');
  ui.innerHTML=`<div class="ui-backdrop" data-close-ui></div>
  <aside class="cart-drawer" id="cartDrawer" aria-hidden="true" aria-labelledby="cartTitle"><div class="drawer-head"><div><p class="eyebrow">Your selection</p><h2 id="cartTitle">Bag</h2></div><button class="close-ui" data-close-ui aria-label="Close bag">×</button></div><div class="cart-items" id="cartItems"></div><div class="cart-summary"><div><span>Subtotal</span><strong id="cartSubtotal">₹0</strong></div><p>Shipping calculated when checkout becomes available.</p><button class="checkout-note" type="button" disabled>Checkout — coming soon</button><small>Secure checkout will be connected with the store backend.</small></div></aside>
  <section class="ui-modal size-modal" id="sizeModal" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="sizeTitle"><button class="close-ui" data-close-ui aria-label="Close size selection">×</button><p class="eyebrow">Choose an option</p><h2 id="sizeTitle">Select size</h2><p id="sizeProduct"></p><div class="size-options" id="sizeOptions"></div><button class="confirm-add" id="confirmAdd" type="button" disabled>Add to bag</button><a class="size-help" href="size-guide.html">View size guide ↗</a></section>
  <section class="ui-modal search-modal" id="searchModal" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="searchTitle"><button class="close-ui" data-close-ui aria-label="Close search">×</button><p class="eyebrow">Find your Aurelyne</p><h2 id="searchTitle">Search</h2><label class="sr-only" for="siteSearch">Search products and collections</label><input id="siteSearch" type="search" placeholder="Try sarees, gowns or jewelry" autocomplete="off"><div class="search-results" id="searchResults"></div></section>`;
  body.append(ui);
  const toast=document.querySelector('#toast')||(()=>{const el=document.createElement('div');el.id='toast';el.className='toast';el.role='status';body.append(el);return el})();
  const backdrop=document.querySelector('.ui-backdrop'), panels=document.querySelectorAll('.cart-drawer,.ui-modal');
  const announce=message=>{toast.textContent=message;toast.classList.add('show');clearTimeout(announce.timer);announce.timer=setTimeout(()=>toast.classList.remove('show'),2200)};
  const closeUI=()=>{panels.forEach(el=>{el.classList.remove('open');el.setAttribute('aria-hidden','true')});backdrop.classList.remove('open');body.classList.remove('ui-open')};
  const openUI=target=>{closeMenu();closeUI();target.classList.add('open');target.setAttribute('aria-hidden','false');backdrop.classList.add('open');body.classList.add('ui-open');setTimeout(()=>target.querySelector('input,button:not(.close-ui)')?.focus(),80)};
  document.querySelectorAll('[data-close-ui]').forEach(el=>el.addEventListener('click',closeUI));

  const updateCount=()=>{const total=cart.reduce((sum,item)=>sum+item.quantity,0);document.querySelectorAll('#cartCount').forEach(el=>el.textContent=total)};
  const renderCart=()=>{const items=document.querySelector('#cartItems');items.innerHTML=cart.length?cart.map((item,index)=>`<article class="cart-item"><img src="${item.image}" alt=""><div><h3>${item.name}</h3><p>${item.option}</p><strong>${money(item.price)}</strong><div class="quantity"><button type="button" data-cart-action="minus" data-index="${index}" aria-label="Reduce quantity">−</button><span>${item.quantity}</span><button type="button" data-cart-action="plus" data-index="${index}" aria-label="Increase quantity">+</button><button class="remove-item" type="button" data-cart-action="remove" data-index="${index}">Remove</button></div></div></article>`).join(''):'<div class="empty-state"><p>Your bag is ready for something new.</p><a href="index.html#new">Explore new arrivals ↗</a></div>';document.querySelector('#cartSubtotal').textContent=money(cart.reduce((sum,item)=>sum+item.price*item.quantity,0));updateCount()};
  document.querySelector('#cartItems').addEventListener('click',event=>{const button=event.target.closest('[data-cart-action]');if(!button)return;const i=Number(button.dataset.index),action=button.dataset.cartAction;if(action==='plus')cart[i].quantity++;if(action==='minus')cart[i].quantity=Math.max(1,cart[i].quantity-1);if(action==='remove')cart.splice(i,1);write(CART_KEY,cart);renderCart()});

  const productFrom=button=>{const card=button.closest('.product,.collection-product'),context=`${document.title} ${card.textContent}`;return{name:card.querySelector('h3')?.textContent.trim()||'Aurelyne product',details:card.querySelector('p')?.textContent.trim()||'',price:price(card.querySelector('strong')?.textContent),image:card.querySelector('img')?.getAttribute('src')||'',type:/jewel|necklace|earring|bangle/i.test(context)?'jewelry':/saree|lehenga/i.test(context)?'saree':'apparel'}};
  const openSize=button=>{activeProduct=productFrom(button);const choices=activeProduct.type==='jewelry'?['One Size']:activeProduct.type==='saree'?['Free Size']:['XS','S','M','L','XL'];document.querySelector('#sizeTitle').textContent=activeProduct.type==='jewelry'?'Confirm selection':'Select size';document.querySelector('#sizeProduct').textContent=`${activeProduct.name} · ${activeProduct.details}`;document.querySelector('#sizeOptions').innerHTML=choices.map(choice=>`<button type="button" data-option="${choice}">${choice}</button>`).join('');const confirm=document.querySelector('#confirmAdd');confirm.disabled=true;confirm.dataset.option='';openUI(document.querySelector('#sizeModal'))};
  document.querySelectorAll('.quick-add,.collection-product-info > button').forEach(button=>{button.type='button';button.addEventListener('click',()=>openSize(button))});
  document.querySelector('#sizeOptions').addEventListener('click',event=>{const button=event.target.closest('[data-option]');if(!button)return;document.querySelectorAll('#sizeOptions button').forEach(el=>el.classList.toggle('selected',el===button));const confirm=document.querySelector('#confirmAdd');confirm.disabled=false;confirm.dataset.option=button.dataset.option});
  document.querySelector('#confirmAdd').addEventListener('click',event=>{const option=event.currentTarget.dataset.option;if(!activeProduct||!option)return;const existing=cart.find(item=>item.name===activeProduct.name&&item.option===option);existing?existing.quantity++:cart.push({...activeProduct,option,quantity:1});write(CART_KEY,cart);renderCart();closeUI();announce(`${activeProduct.name} added to bag`)});
  document.querySelectorAll('.bag-btn').forEach(button=>{button.type='button';button.setAttribute('aria-label','Open shopping bag');button.addEventListener('click',()=>{renderCart();openUI(document.querySelector('#cartDrawer'))})});

  const links=[['New arrivals','index.html#new'],['Dresses & gowns','index.html#dresses'],['Sarees & lehengas','index.html#ethnic'],['Fine jewelry','index.html#jewelry'],['Everyday essentials','index.html#essentials'],['Size guide','size-guide.html'],['Contact','contact.html']], local=[...document.querySelectorAll('.product h3,.collection-product h3')].map(el=>[el.textContent.trim(),'index.html#new']), all=[...links,...local];
  const renderSearch=query=>{const found=all.filter(([name])=>name.toLowerCase().includes(query.toLowerCase()));document.querySelector('#searchResults').innerHTML=found.length?found.map(([name,href])=>`<a href="${href}">${name}<span>↗</span></a>`).join(''):'<p>No matches yet. Try “saree” or “gown”.</p>'};
  renderSearch('');document.querySelector('#siteSearch').addEventListener('input',event=>renderSearch(event.target.value.trim()));document.querySelectorAll('.icon-btn[aria-label="Search"]').forEach(button=>button.addEventListener('click',()=>openUI(document.querySelector('#searchModal'))));

  const wishlist=new Set(read(WISH_KEY));document.querySelectorAll('.heart').forEach(button=>{const name=button.closest('.product')?.querySelector('h3')?.textContent.trim();if(wishlist.has(name)){button.classList.add('active');button.textContent='♥';button.setAttribute('aria-pressed','true')}button.addEventListener('click',()=>{const active=button.classList.toggle('active');button.textContent=active?'♥':'♡';button.setAttribute('aria-pressed',String(active));active?wishlist.add(name):wishlist.delete(name);write(WISH_KEY,[...wishlist]);announce(active?'Saved to wishlist':'Removed from wishlist')})});
  document.querySelectorAll('.icon-btn[aria-label="Wishlist"]').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#new')?.scrollIntoView({behavior:'smooth'});announce(wishlist.size?`${wishlist.size} saved item${wishlist.size===1?'':'s'} — shown below`:'Your wishlist is empty. Tap a heart to save a style.')}));

  const menuButton=document.querySelector('.menu-btn'),menu=document.querySelector('.site-header nav');function closeMenu(){if(!menu||!menuButton)return;menu.classList.remove('open');body.classList.remove('menu-open');menuButton.setAttribute('aria-expanded','false')}
  if(menu&&menuButton){menu.id='main-menu';menuButton.setAttribute('aria-controls','main-menu');menuButton.setAttribute('aria-expanded','false');menuButton.addEventListener('click',()=>{const opening=!menu.classList.contains('open');menu.classList.toggle('open',opening);body.classList.toggle('menu-open',opening);menuButton.setAttribute('aria-expanded',String(opening))});menu.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu))}
  document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeMenu();closeUI()}});window.addEventListener('resize',()=>{if(innerWidth>800)closeMenu()});
  const newsletter=document.querySelector('#newsletter');if(newsletter)newsletter.addEventListener('submit',event=>{event.preventDefault();const input=newsletter.querySelector('input[type="email"]'),message=document.querySelector('#formMessage');if(!input.checkValidity()){message.textContent='Please enter a valid email address.';input.focus();return}message.textContent='Thanks — your email is ready. Delivery will activate when our mailing service launches.';newsletter.reset()});
  document.querySelectorAll('[data-demo-form]').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();if(!form.checkValidity()){form.reportValidity();return}form.querySelector('[role="status"]').textContent=form.dataset.demoMessage||'Thanks. This request is ready to send when our backend goes live.'}));
  renderCart();
})();
