(() => {
  const CART_ID='chaanavya-shopify-cart-v1', DEMO_KEY='chaanavya-cart-v1', WISH_KEY='chaanavya-wishlist-v1', body=document.body;
  const read=(key,fallback=null)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}, write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money=value=>new Intl.NumberFormat('en-IN',{style:'currency',currency:value?.currencyCode||'INR',maximumFractionDigits:2}).format(Number(value?.amount??value??0));
  let live=false, cart=null, demo=read(DEMO_KEY,[]), activeProduct=null;
  async function api(action,variables={}){const response=await fetch('/api/shopify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,variables})}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Store service unavailable');return payload}
  const ui=document.createElement('div');
  ui.innerHTML=`<div class="ui-backdrop" data-close-ui></div><aside class="cart-drawer" id="cartDrawer" aria-hidden="true"><div class="drawer-head"><div><p class="eyebrow">Your selection</p><h2>Bag</h2></div><button class="close-ui" data-close-ui aria-label="Close bag">×</button></div><div class="cart-items" id="cartItems"></div><div class="cart-summary"><div><span>Subtotal</span><strong id="cartSubtotal">₹0</strong></div><p>Shipping and taxes are calculated at checkout.</p><button class="checkout-note" id="checkoutButton" disabled>Secure checkout</button><small id="checkoutStatus">Checkout is secured by Shopify.</small></div></aside><section class="ui-modal size-modal" id="sizeModal" role="dialog" aria-modal="true" aria-hidden="true"><button class="close-ui" data-close-ui>×</button><p class="eyebrow">Choose an option</p><h2 id="sizeTitle">Select option</h2><p id="sizeProduct"></p><div class="size-options" id="sizeOptions"></div><button class="confirm-add" id="confirmAdd" disabled>Add to bag</button><a class="size-help" href="size-guide.html">View size guide ↗</a></section><section class="ui-modal search-modal" id="searchModal" role="dialog" aria-modal="true" aria-hidden="true"><button class="close-ui" data-close-ui>×</button><p class="eyebrow">Find your Chaanavya</p><h2>Search</h2><input id="siteSearch" type="search" placeholder="Try sarees, gowns or jewelry"><div class="search-results" id="searchResults"></div></section>`;body.append(ui);
  const toast=document.querySelector('#toast')||(()=>{const e=document.createElement('div');e.id='toast';e.className='toast';e.role='status';body.append(e);return e})(), backdrop=document.querySelector('.ui-backdrop'), panels=document.querySelectorAll('.cart-drawer,.ui-modal');
  const announce=message=>{toast.textContent=message;toast.classList.add('show');clearTimeout(announce.timer);announce.timer=setTimeout(()=>toast.classList.remove('show'),2200)}, closeUI=()=>{panels.forEach(e=>{e.classList.remove('open');e.setAttribute('aria-hidden','true')});backdrop.classList.remove('open');body.classList.remove('ui-open')}, openUI=target=>{closeMenu();closeUI();target.classList.add('open');target.setAttribute('aria-hidden','false');backdrop.classList.add('open');body.classList.add('ui-open')};
  document.querySelectorAll('[data-close-ui]').forEach(e=>e.addEventListener('click',closeUI));
  const lines=()=>live?(cart?.lines?.nodes||[]).map(line=>({id:line.id,quantity:line.quantity,name:line.merchandise.product.title,option:line.merchandise.title==='Default Title'?'':line.merchandise.title,image:line.merchandise.image?.url||line.merchandise.product.featuredImage?.url||'',price:line.merchandise.price})):demo.map((item,i)=>({...item,id:String(i),price:{amount:item.price,currencyCode:'INR'}}));
  function renderCart(){const items=lines();document.querySelector('#cartItems').innerHTML=items.length?items.map(item=>`<article class="cart-item"><img src="${esc(item.image)}" alt=""><div><h3>${esc(item.name)}</h3><p>${esc(item.option)}</p><strong>${money(item.price)}</strong><div class="quantity"><button data-cart-action="minus" data-id="${esc(item.id)}">−</button><span>${item.quantity}</span><button data-cart-action="plus" data-id="${esc(item.id)}">+</button><button class="remove-item" data-cart-action="remove" data-id="${esc(item.id)}">Remove</button></div></div></article>`).join(''):'<div class="empty-state"><p>Your bag is ready for something new.</p><a href="new-arrivals.html">Explore new arrivals ↗</a></div>';document.querySelector('#cartSubtotal').textContent=money(live?cart?.cost?.subtotalAmount:demo.reduce((s,i)=>s+i.price*i.quantity,0));const checkout=document.querySelector('#checkoutButton');checkout.disabled=!live||!cart?.checkoutUrl||!items.length;document.querySelector('#checkoutStatus').textContent=live?'Checkout is secured by Shopify.':'Shopify checkout activates when the store connection is configured.';document.querySelectorAll('#cartCount').forEach(e=>e.textContent=live?(cart?.totalQuantity||0):demo.reduce((s,i)=>s+i.quantity,0))}
  const unwrap=(payload,action)=>{const result=payload[action];if(!result)throw new Error('Invalid cart response');if(result.userErrors?.length)throw new Error(result.userErrors.map(e=>e.message).join(', '));return result.cart};
  document.querySelector('#cartItems').addEventListener('click',async event=>{const button=event.target.closest('[data-cart-action]');if(!button||button.disabled)return;const item=lines().find(x=>x.id===button.dataset.id);if(!item)return;const quantity=button.dataset.cartAction==='plus'?item.quantity+1:button.dataset.cartAction==='minus'?item.quantity-1:0;button.disabled=true;try{if(live){const action=quantity<=0?'cartLinesRemove':'cartLinesUpdate',variables=quantity<=0?{cartId:cart.id,lineIds:[item.id]}:{cartId:cart.id,lines:[{id:item.id,quantity}]};cart=unwrap(await api(action,variables),action);write(CART_ID,cart.id)}else{const i=Number(item.id);quantity<=0?demo.splice(i,1):demo[i].quantity=quantity;write(DEMO_KEY,demo)}renderCart()}catch(error){announce(error.message);button.disabled=false}});
  const fallbackProduct=button=>{const card=button.closest('.product,.collection-product'),img=card.querySelector('img'),context=`${document.title} ${card.textContent}`;const options=/perfume|fragrance/i.test(context)?['50 ML']:/jewel|necklace|earring|bangle/i.test(context)?['One Size']:/saree|lehenga/i.test(context)?['Free Size']:['XS','S','M','L','XL'],price=Number((card.querySelector('strong')?.textContent||'').replace(/[^0-9]/g,'').slice(0,5));return{name:card.querySelector('h3')?.textContent.trim(),details:card.querySelector('p')?.textContent.trim(),image:img?.src||'',variants:options.map(title=>({id:'',title,availableForSale:true,price:{amount:price,currencyCode:'INR'}}))}};
  const productFrom=button=>{const card=button.closest('.product,.collection-product');return card.dataset.variants?{name:card.dataset.title,details:card.dataset.details,image:card.querySelector('img')?.src||'',variants:JSON.parse(card.dataset.variants)}:fallbackProduct(button)};
  function bindProducts(){document.querySelectorAll('.quick-add,.collection-product-info > button').forEach(button=>{button.type='button';button.onclick=()=>{activeProduct=productFrom(button);const variants=activeProduct.variants.filter(v=>v.availableForSale);document.querySelector('#sizeProduct').textContent=`${activeProduct.name} · ${activeProduct.details||''}`;document.querySelector('#sizeOptions').innerHTML=variants.map((v,i)=>`<button data-index="${i}">${esc(v.title==='Default Title'?'One Size':v.title)}</button>`).join('')||'<p>Currently unavailable.</p>';const confirm=document.querySelector('#confirmAdd');confirm.disabled=true;delete confirm.dataset.index;openUI(document.querySelector('#sizeModal'))}})}
  document.querySelector('#sizeOptions').onclick=event=>{const button=event.target.closest('[data-index]');if(!button)return;document.querySelectorAll('#sizeOptions button').forEach(e=>e.classList.toggle('selected',e===button));const confirm=document.querySelector('#confirmAdd');confirm.disabled=false;confirm.dataset.index=button.dataset.index};
  document.querySelector('#confirmAdd').onclick=async event=>{const variant=activeProduct?.variants?.filter(v=>v.availableForSale)[Number(event.currentTarget.dataset.index)];if(!variant)return;event.currentTarget.disabled=true;try{if(live){const action=cart?'cartLinesAdd':'cartCreate',variables=cart?{cartId:cart.id,lines:[{merchandiseId:variant.id,quantity:1}]}:{input:{lines:[{merchandiseId:variant.id,quantity:1}]}};cart=unwrap(await api(action,variables),action);write(CART_ID,cart.id)}else{const option=variant.title==='Default Title'?'One Size':variant.title,existing=demo.find(i=>i.name===activeProduct.name&&i.option===option);existing?existing.quantity++:demo.push({name:activeProduct.name,option,image:activeProduct.image,price:Number(variant.price.amount),quantity:1});write(DEMO_KEY,demo)}renderCart();closeUI();announce(`${activeProduct.name} added to bag`)}catch(error){announce(error.message);event.currentTarget.disabled=false}};
  document.querySelectorAll('.bag-btn').forEach(button=>{button.type='button';button.onclick=()=>{renderCart();openUI(document.querySelector('#cartDrawer'))}});document.querySelector('#checkoutButton').onclick=()=>{if(cart?.checkoutUrl)location.assign(cart.checkoutUrl)};
  function renderProducts(products){const page=location.pathname.split('/').pop()||'index.html',grid=document.querySelector(page==='index.html'?'#shop':'.collection-products');if(!grid)return;const patterns={'dresses.html':/dress|gown|blouse/i,'ethnic-festive.html':/saree|lehenga|ethnic|festive|bridal/i,'jewelry.html':/jewel|necklace|earring|bangle|ring/i,'essentials.html':/essential|knit|perfume|fragrance|parfum/i};let selected=products.filter(p=>!patterns[page]||patterns[page].test(`${p.title} ${p.productType} ${(p.tags||[]).join(' ')}`));if(!selected.length)selected=products;if(page==='index.html')selected=selected.slice(0,4);const home=page==='index.html';grid.innerHTML=selected.map(p=>{const v=p.variants.nodes.find(x=>x.availableForSale)||p.variants.nodes[0];if(!v)return'';const image=p.featuredImage||v.image||{},details=p.description||p.productType||'',data=`data-title="${esc(p.title)}" data-details="${esc(details)}" data-variants="${esc(JSON.stringify(p.variants.nodes))}"`;return home?`<article class="product" ${data}><div class="product-image"><img loading="lazy" src="${esc(image.url||'')}" alt="${esc(image.altText||p.title)}"><button class="heart" aria-label="Wishlist">♡</button></div><div class="product-info"><div><h3>${esc(p.title)}</h3><p>${esc(details)}</p></div><strong>${money(v.price)}</strong></div><button class="quick-add">Quick add</button></article>`:`<article class="collection-product" ${data}><img loading="lazy" src="${esc(image.url||'')}" alt="${esc(image.altText||p.title)}"><div class="collection-product-info"><h3>${esc(p.title)}</h3><p>${esc(details)}</p><strong>${money(v.price)}</strong><button>Add to bag</button></div></article>`}).join('')}
  const links=[['New arrivals','new-arrivals.html'],['Dresses & gowns','dresses.html'],['Sarees & lehengas','ethnic-festive.html'],['Fine jewelry','jewelry.html'],['Essentials & fragrance','essentials.html'],['Track order','track-order.html'],['Size guide','size-guide.html'],['Contact','contact.html']];
  function setupSearch(products=[]){const all=[...links,...products.map(p=>[p.title,'#collection'])],render=query=>{const found=all.filter(([name])=>name.toLowerCase().includes(query.toLowerCase()));document.querySelector('#searchResults').innerHTML=found.length?found.map(([name,href])=>`<a href="${href}">${esc(name)}<span>↗</span></a>`).join(''):'<p>No matches yet.</p>'};render('');document.querySelector('#siteSearch').oninput=e=>render(e.target.value.trim())}
  document.querySelectorAll('.icon-btn[aria-label="Search"]').forEach(button=>button.onclick=()=>openUI(document.querySelector('#searchModal')));
  function setupWishlist(){const wishlist=new Set(read(WISH_KEY,[]));document.querySelectorAll('.heart').forEach(button=>{const name=button.closest('.product')?.querySelector('h3')?.textContent.trim();button.onclick=()=>{const on=button.classList.toggle('active');button.textContent=on?'♥':'♡';on?wishlist.add(name):wishlist.delete(name);write(WISH_KEY,[...wishlist]);announce(on?'Saved to wishlist':'Removed from wishlist')}})}
  const menuButton=document.querySelector('.menu-btn'),menu=document.querySelector('.site-header nav');function closeMenu(){if(!menu||!menuButton)return;menu.classList.remove('open');body.classList.remove('menu-open');menuButton.setAttribute('aria-expanded','false')}if(menu&&menuButton){menu.id='main-menu';menuButton.onclick=()=>{const open=!menu.classList.contains('open');menu.classList.toggle('open',open);body.classList.toggle('menu-open',open);menuButton.setAttribute('aria-expanded',String(open))}}document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();closeUI()}});
  document.querySelectorAll('form').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const status=form.querySelector('[role=status]')||document.querySelector('#formMessage');if(status)status.textContent='Thanks — your details are ready.'}));
  async function boot(){setupSearch();bindProducts();setupWishlist();renderCart();try{const payload=await api('products',{first:50}),products=payload.products?.nodes||[];live=true;if(products.length){renderProducts(products);bindProducts();setupWishlist();setupSearch(products)}const id=read(CART_ID,'');if(id){try{cart=(await api('cart',{id})).cart;if(!cart)localStorage.removeItem(CART_ID)}catch{localStorage.removeItem(CART_ID)}}renderCart()}catch(error){console.info('Shopify fallback active:',error.message)}}boot();
})();
